version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "auth-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11otlm1qgtcw0"
s3_prefix = "auth-lambda"
region = "eu-west-1"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
